# Generated by Django 3.0.3 on 2020-03-21 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Metagenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetagenomeAssembledGenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness', models.FloatField()),
                ('purity', models.FloatField()),
                ('gc', models.FloatField()),
                ('coverage', models.FloatField()),
                ('gdbtk', models.TextField()),
                ('taxon', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
                ('metagenome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Metagenome')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedJobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('result', models.FileField(upload_to='uploaded_results/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pangenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness', models.FloatField()),
                ('purity', models.FloatField()),
                ('heterogeneity', models.FloatField()),
                ('taxon', models.TextField()),
                ('mag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.MetagenomeAssembledGenome')),
                ('metagenome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Metagenome')),
            ],
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.CreateModel(
            name='MajorityVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.TextField()),
                ('superkingdom', models.TextField()),
                ('phylum', models.TextField()),
                ('class_biology', models.TextField()),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.CreateModel(
            name='Kmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('date_run', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(default='a job needs a description')),
                ('type_of_job', models.CharField(choices=[('BN', 'Binning'), ('PG', 'Pangenome')], default='BN', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.AddField(
            model_name='contig',
            name='metagenome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Metagenome'),
        ),
    ]
