# Generated by Django 3.0.3 on 2020-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_auto_20200322_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='description',
            field=models.TextField(blank=True, default='A file needs a description.'),
        ),
    ]
