# Generated by Django 3.0.3 on 2020-03-22 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_auto_20200322_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
