# Generated by Django 3.0.3 on 2020-02-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0004_auto_20200210_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='descripton',
            field=models.TextField(default='a job needs a description'),
        ),
    ]
