# Generated by Django 3.0.3 on 2020-02-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0005_auto_20200216_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descripton',
            new_name='description',
        ),
    ]
