# Generated by Django 3.0.3 on 2020-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0006_auto_20200216_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type_of_job',
            field=models.CharField(choices=[('BN', 'Binning'), ('PG', 'Pangenome')], default='BN', max_length=2),
        ),
    ]
