# Generated by Django 3.0.3 on 2020-03-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0007_job_type_of_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinningJobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contig', models.TextField()),
                ('cluster', models.CharField(max_length=150)),
                ('completeness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('purity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('taxid', models.CharField(max_length=150)),
                ('superkingdom', models.TextField()),
                ('phylum', models.TextField()),
                ('class_biology', models.TextField()),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('x', models.DecimalField(decimal_places=2, max_digits=6)),
                ('y', models.DecimalField(decimal_places=2, max_digits=6)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Job')),
            ],
        ),
    ]
