# Generated by Django 3.0.3 on 2020-03-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0008_binningjobresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binningjobresult',
            name='class_biology',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='cluster',
            field=models.CharField(default='BLANK', max_length=150),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='completeness',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='contig',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='family',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='genus',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='order',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='phylum',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='purity',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='species',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='superkingdom',
            field=models.TextField(default='BLANK'),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='taxid',
            field=models.CharField(default='BLANK', max_length=150),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='x',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='binningjobresult',
            name='y',
            field=models.FloatField(default=0.01),
        ),
    ]
