# Generated by Django 3.0.3 on 2020-03-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0009_auto_20200313_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.CreateModel(
            name='Kmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.CreateModel(
            name='MajorityVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.TextField()),
                ('superkingdom', models.TextField()),
                ('phylum', models.TextField()),
                ('class_biology', models.TextField()),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
            ],
        ),
        migrations.CreateModel(
            name='Metagenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetagenomeAssembledGenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness', models.FloatField()),
                ('purity', models.FloatField()),
                ('gc', models.FloatField()),
                ('coverage', models.FloatField()),
                ('gdbtk', models.TextField()),
                ('taxon', models.TextField()),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Contig')),
                ('metagenome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Metagenome')),
            ],
        ),
        migrations.CreateModel(
            name='Pangenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness', models.FloatField()),
                ('purity', models.FloatField()),
                ('heterogeneity', models.FloatField()),
                ('taxon', models.TextField()),
                ('mag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.MetagenomeAssembledGenome')),
                ('metagenome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Metagenome')),
            ],
        ),
        migrations.DeleteModel(
            name='BinningJobResult',
        ),
        migrations.AddField(
            model_name='contig',
            name='metagenome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.Metagenome'),
        ),
    ]
