# Generated by Django 3.0.3 on 2020-03-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0011_jobresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobResult',
            new_name='UploadedJobResult',
        ),
    ]
