# Generated by Django 3.0.3 on 2020-03-20 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0012_auto_20200320_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedjobresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedjobresult',
            name='result',
            field=models.FileField(upload_to='uploaded_results/'),
        ),
    ]
