# Generated by Django 3.0.3 on 2020-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_auto_20200207_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='descripton',
            field=models.TextField(default='a title'),
        ),
    ]
